### ISSUE TITLE
Twemoji and Emoji One columns are mixed up

### ISSUE THREAD

**Issue by kurisubrooks** [rodrigopolo/minEmoji#10]
twemoji are in the emoji one column, and emoji one emoji are in the twemoji column

**Comment by rodrigopolo** [comment]
Nop, is the Apple emojis wich are filling the missing Twitter emojis in all sets, Twemoji said that it will provide new emojis soon… I’ll wait seated, Emoji One (which BTW is the best option available online) will release a new set on November and when that happens I will update the sprites, the new Emoji One collection is gorgeous.

**Comment by kurisubrooks** [comment]
Ah sorry, I was looking here. http://rodrigopolo.com/files/emojilist/
The columns are screwed up, you might want to fix it.

**Comment by rodrigopolo** [comment]
Oh, Indeed, I did a mashup there, I'll fix it soon.
