### ISSUE TITLE
Support for iOS 9.1 Emojis

### ISSUE THREAD

**Issue by bennyn** [rodrigopolo/minEmoji#11]
There are new Emojis with iOS 9.1: http://emojipedia.org/new-ios-9-1/

There is for example an up-side-down Emoji (http://emojipedia.org/upside-down-face/) which cannot be rendered. Is it possible to add support for it?

**Comment by rodrigopolo** [comment]
The latest release does, try it:
http://rodrigopolo.github.io/minEmoji/minEmoji/demo.html
