### ISSUE TITLE
Using jMinEmoji2 is there a way to use the standalone minEmoji() function?

### ISSUE THREAD

**Issue by trevorgehman** [rodrigopolo/minEmoji#12]
I'm using the jMinEmoji2 Jquery plugin, but I also need a way to replace the emojis on a string. I see that I can use the standalone minEmoji to accomplish this, but when I include both there is some conflict with the stylesheets.

What's the best way to go about this?

**Comment by trevorgehman** [comment]
Just FYI, I can do this:

```
return $('<div/>').text(string).minEmoji().html();
```

But I was hoping there was a faster way to accomplish this.

**Comment by rodrigopolo** [comment]
There is a single function for that, take a look to the example source:
https://github.com/rodrigopolo/minEmoji/blob/master/minEmoji/demo.html

This is from this example:
https://github.com/rodrigopolo/minEmoji/tree/master/minEmoji

Sorry for the delay, I have too much work lately
