### ISSUE TITLE
Re-convert image tags to emoji for inputs.

### ISSUE THREAD

**Issue by bugrayuksel** [rodrigopolo/minEmoji#13]
Hello,

Thanks for your good job. I want to ask you that how can i convert back image tags to emoji for editing databases values in form inputs?

I insert the emojis to database; but when a user wants to edit it; input text show <img src=emoji/1fe2n.png .... > etc. I have to show emojis in the form input.

What is your suggestion for this?

Thanks.

**Comment by rodrigopolo** [comment]
Only convert emojis on presentation (views) but store the emojis as they are into the DB
