### ISSUE TITLE
Update the SVG's

### ISSUE THREAD

**Issue by OliverKK** [rodrigopolo/minEmoji#15]
Hello, 
great library! I like and use it!

Are u thinking about to update the list of svg's? There are still some missing.

Cheers 
Oliver KK

**Comment by rodrigopolo** [comment]
Which one are missing?
BTW I try to use the emojis used on iOS, OS X, Android and Windows devices, not the 100% standard ones, the reason behind this decision is simple, the only way the average user input some emoji is using those devices and OSs.

**Comment by OliverKK** [comment]
Hello,
thank you for your reply.
For example following are missing and a couple more: emj1594, emj1426, emj1598, emj1427

Okay. I got your point.
Cheers OliverKK
