### ISSUE TITLE
Is it free to use?

### ISSUE THREAD

**Issue by YingshanDeng** [rodrigopolo/minEmoji#16]
Hi, thank you for your work 👍  And I want to use the minEmoji_iOS8 to my project. But I don't know the emoji images(Apple Sprites) whether are free to use or not ?

**Comment by rodrigopolo** [comment]
To be completely honest, I'm not a lawyer, I guess they have no problem if some one use them for any non-commercial project, even Github use them, but I guess they would't think is ok if Samsung or Microsoft use them.

BTW you can switch to other sprite library, like Emoji One which is free to use.
