### ISSUE TITLE
Apple’s new diverse emoji

### ISSUE THREAD

**Issue by bennyn** [rodrigopolo/minEmoji#5]
Hey, are you planning to support Apple's news diversity emojis? There are more than 300 new Emoji icons.

**Comment by rodrigopolo** [comment]
Indeed, I just need to find some free time to do it.

**Comment by rodrigopolo** [comment]
I have created an early version but there are no other sources for the images than Apple PNGs, so until there are more images there is not much to do, here is the alpha version:
http://rodrigopolo.github.io/minEmoji/minEmoji_iOS8/demo.html

**Comment by bennyn** [comment]
Great! Happy to hear that! By the way, can you create a [release](https://github.com/rodrigopolo/minEmoji/releases) on GitHub for it? So I can link your library in my bower file.

**Comment by rodrigopolo** [comment]
I have created a new (different) version, read here the reasons of doing this:
https://github.com/rodrigopolo/minEmoji/tree/master/jMinEmoji2

Here are the new demos:
http://rodrigopolo.github.io/minEmoji/jMinEmoji2/demo.html
http://rodrigopolo.github.io/minEmoji/minEmoji_iOS8/demo.html

**Comment by bennyn** [comment]
Cool! Thank you very very much!! This is so helpful !!! Thanks! :+1:
