### ISSUE TITLE
"is_safari" check recognizes PhantomJS as Safari

### ISSUE THREAD

**Issue by bennyn** [rodrigopolo/minEmoji#6]
In my webapp I am using `jMinEmoji2`. To test my webapp I am using [Jasmine](http://jasmine.github.io/), a behavior-driven development framework for testing JavaScript code.

Jasmine is executed by [PhantomJS](http://phantomjs.org/), a headless WebKit browser. In my tests I was checking if Emojis are correctly replaced by the minEmoji library (with code like `'<span class="em emj115"></span>'`) but I realized that they are not replaced.

When checking the minEmij code, I saw that it tests if a browser is a Safari browser, to not replace Emojis on Apple devices. But unfortunately PhantomJS uses the user agent `Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34`, which is recognized as Safari.

Therefore I suggest to exclude PhantomJS from the `is_safari` check.

**Comment by rodrigopolo** [comment]
Fixed in version 1.0.2
