### ISSUE TITLE
Baby Bottle is rendered as Clinking Beer Mugs

### ISSUE THREAD

**Issue by bennyn** [rodrigopolo/minEmoji#7]
I just noticed that the minEmoji library renders the Baby Bottle (🍼) to `em emj502` which are clinking Beer Mugs (🍻). This is very funny but unfortunately not the expected behaviour. :grin: 

Baby Bottle:
http://emojipedia.org/baby-bottle/

Clinking Beer Mugs:
http://emojipedia.org/clinking-beer-mugs/

**Comment by bennyn** [comment]
Just checked the source code and found the bug here: 
https://raw.githubusercontent.com/rodrigopolo/minEmoji/master/jMinEmoji2/js/jMinEmoji2.js

Code:
`"🍻":502,"🍼":502,`

So both (the clinking beer mugs and the baby bottle) are mapped to `502`. But I couldn't find baby bottle in the `ios8sprite.png`. So does it exist?

**Comment by rodrigopolo** [comment]
It is the 503 code I belive but I have to check... I do this on OS X, I'll do it some time later, thanks.

**Comment by rodrigopolo** [comment]
Indeed, code 503, I just have to be sure on OS X, here is the full mapping:
http://rodrigopolo.com/files/emojilist/

**Comment by bennyn** [comment]
Thanks for the quick response! Is it only `jMinEmoji2.js` which is affected? Because then I can open a pull request otherwise I will need your help. :)

**Comment by bennyn** [comment]
I checked `em emj503` but it's a Smiley and not a baby bottle. :-\

**Comment by rodrigopolo** [comment]
Fixed in version 1.0.2
