### ISSUE TITLE
The sprite could be smaller easily

### ISSUE THREAD

**Issue by manfreed** [rodrigopolo/minEmoji#9]
Hi!

As you mentioned in the readme of jMinEmoji2, the sprite is quite big. 950K is too much especially for mobile sites. 

Luckily the size of that emoji.png can be easily reduced just by recompressing it. I've been using tinypng.com for a while now, and they reduced the size from 950K to 212K, but you can use anything that works for you :)

**Comment by rodrigopolo** [comment]
You are right, they use quantization in order to reduce png colors, which reduce quality, but overall it doesn’t compromise the emoji, so I use [pngquant](http://pngquant.org) in combination with other tools and updated the repo, commit: 06bbdb5
